#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Provisionar o projeto Supabase novo do Hub Geotech
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

# Credenciais salvas fora de qualquer repo — isso é pro projeto Hub que ainda
# não existe como código; quando o repo do Hub nascer, mova esse arquivo (ou
# copie os valores) pro .env dele.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/hub-geotech-supabase.env"

banner "Hub Geotech — novo projeto Supabase (schema unificado)"

# ── Stage 1: conta separada ────────────────────────────────────────────────
stage "Conta Supabase separada"
say "Este projeto precisa nascer numa conta DIFERENTE da que já hospeda"
say "Plantio/Preparo e Expo_safra (Colheita) — aquela já está no limite de"
say "2 projetos free. Isso evita mexer nos sistemas em produção enquanto"
say "construímos e validamos o schema novo."
open_url "https://supabase.com/dashboard/sign-up"
step "Cadastre-se com um e-mail/GitHub DIFERENTE do usado na conta principal."
step "Se já tiver essa 2ª conta pronta, só faça login nela."
confirm "Está logado na conta separada?" || warn "confirme o login antes de seguir pra próxima etapa"

# ── Stage 2: criar o projeto ────────────────────────────────────────────────
stage "Criar o projeto novo"
say "Nome sugerido: hub-geotech. Região: South America (São Paulo) — mais"
say "perto do time de campo. Plano: Free (padrão, não precisa mexer)."
open_url "https://supabase.com/dashboard/new"
step "Organization: crie uma nova (ou use a que já existir nessa conta)."
step "Name: hub-geotech"
step "Database Password: gere uma senha forte — o Supabase pode gerar pra você."
warn "Anote essa senha em algum lugar seguro (gerenciador de senhas) — é a"
warn "senha de conexão direta com o Postgres, diferente das API keys."
ask_secret DB_PASSWORD "Cole aqui a senha do banco (só pra guardar no .env local):"
step "Region: South America (São Paulo) — se não estiver disponível, escolha a mais próxima."
step "Clique em 'Create new project' e aguarde a provisão (leva 1-2 minutos)."
pause "Aguarde o projeto ficar com o status ativo, depois pressione Enter"
write_env DB_PASSWORD "$DB_PASSWORD"

# ── Stage 3: credenciais da API ─────────────────────────────────────────────
stage "Capturar credenciais da API"
say "No projeto criado, vá em Settings → API (ou Project Settings → API Keys)."
step "Copie o 'Project URL' (formato https://xxxxx.supabase.co)."
ask SUPABASE_URL "Cole o Project URL:"
step "Copie a 'anon' / 'publishable' key (começa com sb_publishable_... ou é um JWT longo)."
ask SUPABASE_ANON_KEY "Cole a anon/publishable key:"
step "Clique em 'Reveal' na 'service_role' / 'secret' key e copie."
warn "Essa chave dá acesso total ao banco (bypassa RLS) — NUNCA vai em código"
warn "público (frontend/repo GitHub Pages). É só pra engine de ingestão local."
ask_secret SUPABASE_SERVICE_ROLE_KEY "Cole a service_role/secret key:"
write_env SUPABASE_URL "$SUPABASE_URL"
write_env SUPABASE_ANON_KEY "$SUPABASE_ANON_KEY"
write_env SUPABASE_SERVICE_ROLE_KEY "$SUPABASE_SERVICE_ROLE_KEY"

# ── Stage 4: abrir o SQL Editor ─────────────────────────────────────────────
stage "Abrir o SQL Editor (pronto pra próxima etapa)"
say "A próxima etapa (fora deste wizard) é colar e rodar a migration do"
say "schema 'hub' aqui. Deixe essa aba aberta."
step "No menu lateral do projeto, clique em 'SQL Editor'."
step "Clique em '+ New query' pra abrir um editor em branco."
pause "Com o editor em branco aberto, pressione Enter"

# ── Stage 5: teste de conectividade ─────────────────────────────────────────
stage "Teste de conectividade"
say "Só pra confirmar que o projeto está respondendo antes de aplicar o schema."
step "Cole no editor: select 1;"
step "Clique em 'Run' (ou Ctrl+Enter)."
confirm "Retornou um resultado (1 linha, valor 1) sem erro?" \
  && say "  Projeto ativo e acessível." \
  || warn "Se deu erro, o projeto pode ainda estar provisionando — espere 1 min e tente de novo."

finish
note "Próximo passo (fora deste wizard): aplicar a migration do schema 'hub'"
note "nesse mesmo SQL Editor que você deixou aberto."
