#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: Serviço de envio de arquivos do Hub (Cloudflare Worker + GitHub)
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="$SCRIPT_DIR/hub-geotech-supabase.env"
REPO_ARQUIVOS="lmalerbo/hub-geotech-arquivos"
ORIGENS="http://127.0.0.1:8765,https://lmalerbo.github.io"

# copiar pra área de transferência do Windows (Git Bash)
copiar() { printf '%s' "$1" | clip.exe 2>/dev/null && printf '  %s✓ copiado%s para a área de transferência\n' "$GREEN" "$RESET"; }

banner "Hub Geotech — serviço de envio de arquivos"

# ── Stage 1: repositório de arquivos ──────────────────────────────────────
stage "Repositório de arquivos no GitHub"
say "Os arquivos (.dwg/.zip/.pdf) ficam nas Releases de um repositório só"
say "deles, separado do código. É público porque o Portal baixa sem login."
if gh repo view "$REPO_ARQUIVOS" >/dev/null 2>&1; then
  say "  $REPO_ARQUIVOS já existe — pulando."
elif confirm "Criar $REPO_ARQUIVOS (público, com README) agora?"; then
  gh repo create "$REPO_ARQUIVOS" --public --add-readme \
    --description "Arquivos de projeto publicados pelo Hub Geotech (Plantio, Preparo, Colheita)"
else
  warn "sem esse repositório o envio não funciona — rode o wizard de novo depois"
fi
pause "Enter para continuar"

# ── Stage 2: token do GitHub ──────────────────────────────────────────────
stage "Token do GitHub (só para o repositório de arquivos)"
say "Um token com acesso APENAS ao $REPO_ARQUIVOS — se vazar, não mexe em"
say "mais nada da sua conta."
open_url "https://github.com/settings/personal-access-tokens/new"
step "Token name: hub-geotech-arquivos (Worker)"
step "Expiration: 1 ano (anote a data — precisa renovar antes de vencer)"
step "Repository access: Only select repositories → $REPO_ARQUIVOS"
step "Permissions → Repository permissions → Contents: Read and write"
step "Generate token e COPIE o token (começa com github_pat_)."
note "Não cole aqui: ele vai direto para a Cloudflare no próximo passo."
pause "Com o token copiado, Enter"

# ── Stage 3: criar o Worker ───────────────────────────────────────────────
stage "Criar o Worker na Cloudflare"
open_url "https://dash.cloudflare.com/?to=/:account/workers-and-pages/create"
step "Create Worker → nome: hub-geotech-arquivos → Deploy (o código de exemplo)."
step "Depois: Edit code → apague o código de exemplo."
copiar "$(cat "$SCRIPT_DIR/worker/arquivos.js")"
step "Cole (Ctrl+V) o código do Hub que acabei de copiar → Deploy."
pause "Com o código publicado, Enter"

# ── Stage 4: variáveis e segredo ──────────────────────────────────────────
stage "Configurar o Worker"
say "No Worker: Settings → Variables and Secrets → Add. Uma de cada vez;"
say "aperte Enter aqui pra copiar o próximo valor."
SUPA_URL=$(_existing SUPABASE_URL || true); SUPA_ANON=$(_existing SUPABASE_ANON_KEY || true)
for par in "SUPABASE_URL|Text|$SUPA_URL" "SUPABASE_ANON_KEY|Text|$SUPA_ANON" \
           "GH_REPO|Text|$REPO_ARQUIVOS" "ORIGENS|Text|$ORIGENS"; do
  IFS='|' read -r nome tipo valor <<<"$par"
  step "Add → Type: $tipo → Name: $nome → Value: (Ctrl+V)"
  copiar "$valor"
  pause "Adicionou $nome? Enter"
done
step "Add → Type: Secret → Name: GH_TOKEN → Value: o token do GitHub (passo 2)."
step "Clique em Deploy para salvar as variáveis."
pause "Tudo salvo e publicado? Enter"

# ── Stage 5: endereço e teste ─────────────────────────────────────────────
stage "Endereço do Worker e teste"
step "Na página do Worker, copie o endereço (https://hub-geotech-arquivos.<sua-conta>.workers.dev)."
ask WORKER_URL "Cole o endereço do Worker:"
WORKER_URL="${WORKER_URL%/}"
write_env WORKER_URL "$WORKER_URL"
codigo=$(curl -s -o /dev/null -w '%{http_code}' -X POST "$WORKER_URL/enviar" || true)
if [[ "$codigo" == "401" ]]; then
  say "  ✓ Worker respondeu certo (pediu login, como deve)."
else
  warn "Worker respondeu $codigo (esperado 401). Confira o código e as variáveis."
fi

finish
note "Me avise que terminou: eu coloco o endereço do Worker no app e testo um envio real."
